tracker updates
umami-software/umami pull request #1272
Opened 2022-07-07 09:19 UTC by Maxime-J

As `fetch` was used to replace `navigator.sendBeacon`, it might be good to handle all the requests with it.
It's more convenient than XHR.

If you're okay, this PR :
- replaces XHR by Fetch
- centralizes the requests (no call to collect api without passing through `collect()`)
- adds a parameter to the collect function, for requests which needs to persist on exit/location change,
like it is currently the case with link events (and it can probably be useful for possible future uses)
- applies the same logic in sendEvent as in other functions

2022-07-08 04:52 UTC, rohandebsarkar approved these changes

2022-07-09 09:12 UTC, rohandebsarkar commented on tracker/index.js
> +      options['keepalive'] = true;
I think, all the requests should use the `keepalive` option. Previously, the other requests were sent using XHR, therefore those requests were not persisted.

2022-07-10 15:49 UTC, rohandebsarkar requested changes
I think this should be the structure for fetch requests.

Whether to cache the response could also be checked by `type === 'pageview'`, but the previous one is probably better if any other responses need to cached in the future.

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +  const collect = (type, payload, persist = false) => {
```suggestion
  const collect = (type, payload, cacheResponse = false) => {
```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +      body: JSON.stringify({type, payload}),
```suggestion
      body: JSON.stringify({type, payload}),
      keepalive: true,
```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +    if (!persist) {
```suggestion
    if (cacheResponse) {
```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +      options['keepalive'] = true;
```suggestion

```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +      }),
```suggestion
      })
```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +      true
```suggestion

```

2022-07-10 15:49 UTC, rohandebsarkar commented on tracker/index.js
> +      })
```suggestion
      }),
      true
```

2022-07-11 21:01 UTC, Maxime-J commented
The suggested changes differs a lot from the initial PR, which keeps exactly the same behaviour as now:

Standard requests not resistant to location change/exit, like in XHR, and the answer always cached locally
Specific requests (currently for link events) resistant to location change/exit, like in `navigator.sendBeacon`, without handling the answer cache.

2022-07-12 10:28 UTC, rohandebsarkar commented
Yeah, okay. I'll probably work this on another PR if @mikecao is interested.

2022-07-12 16:33 UTC, mikecao commented
I'm still undecided on this because the reason we went with XHR is to support older browsers. I haven't read up on the state of fetch support yet. Maybe we can create a separate tracker to support older browsers?

2022-07-12 16:58 UTC, rohandebsarkar commented
I understand, but `fetch()` is currently supported by all the major browsers, except Internet Explorer. But Internet Explorer has already been [declared retired on 15 June 2022](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/).

Reference: https://developer.mozilla.org/en-US/docs/Web/API/fetch#browser_compatibility

2022-07-22 13:54 UTC, Maxime-J commented
Understood, actually went with fetch because it was introduced in tracker in a previous commit.
And as Rohan said, it's widely supported now.

I also believe that kind of error wouldn't happen (#1246), not sure though.

2022-08-04 05:45 UTC, mikecao approved these changes

2022-08-04 05:45 UTC, merged