Add Swiss German language locale (de-CH)
umami-software/umami pull request #1870
Opened 2023-04-06 21:20 UTC by kaisteinke

Adds the central swiss "Schwiizerdütsch" locale.

For more info, see:
https://www.eldrid.ch/swgerman.htm
https://en.wikipedia.org/wiki/Swiss_German

2023-04-06 21:30 UTC, pwuersch requested changes
Added some suggestion from my style of writing in „Schwiizerdütsch“

2023-04-06 21:30 UTC, pwuersch commented on lang/de-CH.json
> +  "message.delete-warning": "Alli dezueghörigi Date werdet ebefalls glöscht.",
```suggestion
  "message.delete-warning": "Alli dezueghörige Date werdet ebefalls glöscht.",
```

2023-04-06 21:30 UTC, pwuersch commented on lang/de-CH.json
> +  "message.share-url": "Das isch d'Öffentlichi URL zum Teile für {target}.",
```suggestion
  "message.share-url": "Das isch die öffentlichi URL zum Teile für {target}.",
```

2023-04-08 09:30 UTC, mikecao approved these changes

2023-04-08 09:30 UTC, merged